import Link from "next/link";
import { CalendarCheck, ClipboardList, FileText, Images, PhoneCall, Plus, UserRoundCheck } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { db } from "@/lib/db";
import { faDate, faNumber, statusLabels } from "@/lib/format";

export const dynamic = "force-dynamic";
export default async function DashboardPage() {
  const [newCount, followingCount, appointmentCount, contentCount, mediaCount, latest, logs] = await Promise.all([
    db.consultationRequest.count({ where: { status: "NEW" } }), db.consultationRequest.count({ where: { status: "CONTACTED" } }), db.consultationRequest.count({ where: { status: "APPOINTMENT" } }), db.contentEntry.count(), db.mediaItem.count({ where: { active: true } }), db.consultationRequest.findMany({ take: 7, orderBy: { createdAt: "desc" } }), db.auditLog.findMany({ take: 4, orderBy: { createdAt: "desc" }, include: { user: { select: { name: true } } } }),
  ]);
  const metrics = [["درخواست‌های جدید",newCount,ClipboardList,"text-[#17603f] bg-[#e8f3ed]"],["در حال پیگیری",followingCount,PhoneCall,"text-amber-700 bg-amber-50"],["نوبت‌های ثبت‌شده",appointmentCount,CalendarCheck,"text-blue-700 bg-blue-50"],["محتوای قابل مدیریت",contentCount,FileText,"text-[#17603f] bg-[#e8f3ed]"],["رسانه‌های منتشرشده",mediaCount,Images,"text-purple-700 bg-purple-50"]] as const;
  return <AdminShell active="/admin" title="نمای کلی" description="خلاصه وضعیت درخواست‌ها و فعالیت‌های امروز" action={<Link href="/admin/requests" className="btn-primary min-h-10 px-4 py-2"><Plus size={17} />مشاهده درخواست‌ها</Link>}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,Icon,color]) => <article key={label} className="flex items-center justify-between rounded-xl border border-[#dfe7e2] bg-white p-5"><div><p className="text-sm text-[#66736d]">{label}</p><p className="mt-3 text-3xl font-black text-[#173d2f]">{faNumber.format(value)}</p></div><span className={`grid size-11 place-items-center rounded-full ${color}`}><Icon size={21} /></span></article>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><section className="overflow-hidden rounded-xl border border-[#dfe7e2] bg-white"><div className="flex items-center justify-between border-b border-[#e5ebe8] p-5"><h2 className="font-extrabold">آخرین درخواست‌های مشاوره</h2><Link href="/admin/requests" className="text-xs font-bold text-[#17603f]">مشاهده همه</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-right text-sm"><thead className="bg-[#fafbfa] text-xs text-[#748179]"><tr><th className="p-4">نام</th><th className="p-4">شماره تماس</th><th className="p-4">موضوع</th><th className="p-4">ثبت</th><th className="p-4">وضعیت</th></tr></thead><tbody className="divide-y divide-[#e8edea]">{latest.map((item) => <tr key={item.id} className="hover:bg-[#f7faf8]"><td className="p-4 font-bold">{item.fullName}</td><td className="p-4" dir="ltr">{item.phone}</td><td className="p-4 text-[#66736d]">{item.requestType}</td><td className="p-4 text-xs text-[#7a8780]">{faDate(item.createdAt)}</td><td className="p-4"><span className="rounded-md bg-[#e7f1eb] px-2 py-1 text-xs font-bold text-[#17603f]">{statusLabels[item.status]}</span></td></tr>)}{latest.length === 0 ? <tr><td colSpan={5} className="p-16 text-center text-[#7a8780]">هنوز درخواستی ثبت نشده است.</td></tr> : null}</tbody></table></div></section><aside className="h-fit rounded-xl border border-[#dfe7e2] bg-white p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#e8f3ed] text-[#17603f]"><UserRoundCheck size={19} /></span><h2 className="font-extrabold">آخرین تغییرات</h2></div><div className="mt-5 divide-y divide-[#e7ece9]">{logs.map((log) => <article key={log.id} className="py-4"><p className="text-sm font-semibold leading-6">{log.summary}</p><p className="mt-2 text-xs text-[#85918b]">{log.user?.name || "سیستم"} · {faDate(log.createdAt)}</p></article>)}{logs.length === 0 ? <p className="py-10 text-center text-sm text-[#85918b]">هنوز تغییری ثبت نشده است.</p> : null}</div></aside></div></AdminShell>;
}
